### ISSUE TITLE
The wiki page is not friendly to mobile view

### ISSUE THREAD

**Issue by lijunle** [danieljsummers/FromObjectsToFunctions#1]
Could you please use the source code to manage the articles?

**Comment by danieljsummers** [comment]
I'm looking into ways to push this information out; I'm leaning towards generating the content and putting it out on GitHub Pages.  I'll leave this open until the existing content has been migrated there, and let you know the link.

**Comment by danieljsummers** [comment]
The commit shouldn't have closed the issue.

**Comment by danieljsummers** [comment]
I got the [new site](https://danieljsummers.github.io/FromObjectsToFunctions/) up; it should work much better.

**Comment by lijunle** [comment]
Thank you, it is awesome!

2016年11月27日 10:21，"Daniel J. Summers" <notifications@github.com>写道：
